openapi: 3.0.0
info:
  title: 'Product API'
  version: '0.1'
paths:
  /product:
    get:
      operationId: getProducts
      parameters:
        -
          name: limit
          in: query
          description: 'How many products to return at one time'
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 'Returns the product data'
