name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      ###################
      # Stage 1 - Build #
      ###################
      - name: Checkout latest revision
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install

      - name: Start PHP built-in webserver
        run: php -S localhost:8000 -t public &

      ###########################
      # Stage 2 - Code Analysis #
      ###########################
      - name: Code Style Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run

      - name: Static Code Analysis
        run: vendor/bin/phpstan

      ###################
      # Stage 3 - Tests #
      ###################
      - name: Unit Tests
        run: vendor/bin/phpunit --testsuite Unit

      - name: Integration Tests
        run: vendor/bin/phpunit --testsuite Api

      ####################
      # Stage 4 - Deploy #
      ####################
      - name: Remove dev dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create release artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            public/
            src/
            vendor/
      - name: Create reports artifact
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports/
